# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 07:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Apartment Code')),
                ('floor', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Floor')),
                ('mansard', models.BooleanField(default=False, verbose_name='Mansard')),
                ('square', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Square')),
                ('balcony_square', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Balcony Square')),
                ('loggia_square', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Loggia Square')),
                ('sea_view', models.BooleanField(default=False, verbose_name='Sea View')),
                ('terrace', models.BooleanField(default=False, verbose_name='Terrace Exists')),
                ('lawn', models.BooleanField(default=False, verbose_name='Lawn Exists')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Booked'), (2, 'Sold')], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Apartment Description',
                'verbose_name_plural': 'Apartment Descriptions',
                'ordering': ['layout_type'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Building Name')),
                ('code', models.CharField(max_length=2, verbose_name='Two-letters Code')),
                ('sorting', models.IntegerField(default=100, verbose_name='Sorting')),
                ('description_title', models.CharField(max_length=128, verbose_name='Description Title')),
                ('description', models.TextField(verbose_name='Building Description')),
                ('photo', models.FileField(upload_to='buildings', verbose_name='Building Photo')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='building_photo', verbose_name='photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Building')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Layout Name')),
                ('image', models.FileField(upload_to='layout', verbose_name='Layout Image')),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LayoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Layout Type Name')),
                ('sorting', models.IntegerField(default=100, verbose_name='Sorting')),
            ],
            options={
                'verbose_name': 'Layout Type',
                'verbose_name_plural': 'Layout Types',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Placement Name')),
                ('image', models.FileField(upload_to='placement', verbose_name='Placement Image')),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='apartmentdescription',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='apartmentdescription',
            name='layout_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.LayoutType', verbose_name='Layout Type'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Layout', verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='layout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.LayoutType', verbose_name='Layout Type'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Placement', verbose_name='Placement'),
        ),
    ]
