# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 09:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apartment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='apartmentdescription',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='buildings', verbose_name='Building Photo'),
        ),
    ]
