# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 10:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('announce', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Announce')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-date'],
                'verbose_name': 'News Article',
            },
        ),
    ]
