# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 10:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
