# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='description')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='photo', verbose_name='photo')),
                ('sorting', models.PositiveSmallIntegerField(default=100, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['sorting'],
            },
        ),
    ]
