# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-01 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Office Name')),
                ('sorting', models.IntegerField(default=100, verbose_name='Sorting')),
                ('slug', models.SlugField(max_length=32, verbose_name='Slug')),
                ('address', models.CharField(max_length=256, verbose_name='Office Address')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('lat', models.CharField(default='55.772406', max_length=16, verbose_name='Latitude')),
                ('lng', models.CharField(default='37.638447', max_length=16, verbose_name='Longitude')),
                ('scale', models.IntegerField(default=16, verbose_name='Map scale')),
            ],
            options={
                'verbose_name': 'Office',
                'ordering': ['sorting'],
                'verbose_name_plural': 'Offices',
            },
        ),
    ]
