# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='cert', verbose_name='image')),
                ('sorting', models.IntegerField(default=100, verbose_name='sorting')),
            ],
            options={
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('preview', sorl.thumbnail.fields.ImageField(upload_to='docs', verbose_name='image')),
                ('file', models.FileField(upload_to='docs', verbose_name='file')),
                ('sorting', models.IntegerField(default=100, verbose_name='sorting')),
                ('tech_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='tech info')),
            ],
            options={
                'ordering': ['sorting'],
            },
        ),
    ]
