# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Site Name')),
                ('logo', models.FileField(upload_to='newsportals', verbose_name='Logo')),
                ('link', models.CharField(max_length=256, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'News Portal',
                'verbose_name_plural': 'News Portals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Article Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('link', models.CharField(max_length=256, verbose_name='Article Link')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.NewsPortal', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date'],
            },
        ),
    ]
