# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 11:17
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportal',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(upload_to='newsportals', verbose_name='Logo'),
        ),
    ]
