# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendFlatpage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'static pages',
            },
            bases=('flatpages.flatpage',),
        ),
    ]
