# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 11:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
            },
        ),
    ]
